---
args : #common arguments
 location: 'us-central1' #Bigquery table location
 bucket_name: 'bkt-dmgcp-del-ce-temp'   #bucket to export table into files from Bigquery
 composer_bucket: 'us-central1-dm-composer-d5b3de0f-bucket' #Bucket of dag files,config and sql files
 export_file_name: 'bq_to_gcs_file.csv' #file name for bq to gcs export .csv file
 merged_file_name: 'merged_bq_to_cloudsql_test_file_inc.csv' #file name for merged csv files 
 cloudsql_instance: 'posgre-sql-cisco-poc' #cloudSQL instance name
 cloudsql_project: 'dmgcp-del-ce' #GCP project of cloudSQL instance 
 cloudsql_importuser: 'postgres' #cloudSQL instance user
 vm_instance_user: 'sagar_chavan@jump-host'
 vm_instance_zone: 'us-central1-a'
 mount_directory: "/home/sagar_chavan"
 mysql_host: "172.16.128.107"
 mysql_user: 'dmuser'
 mysql_database: 'my_db'
 mysql_password: 'dmpoc@2022'

 
 
TABLE_CONFIG : #table 1
 project_name : 'dmgcp-del-ce'
 dataset_name: 'DB_CE_TEMP'
 bq_table: 'EMPLOYEE'
 cloudsql_database: 'postgres'
 cloudsql_table: 'EMPLOYEE' 
 cloudsql_staging_table: 'STAGING_EMPLOYEE'
 type_load: 'HIST'     # Type of load must be defined : HIST/INCR
 insert_into_script: 'sql/insert_into_script.sql'
 
 
EMPLOYEE_1 : #table 2
 project_name : 'dmgcp-del-ce'
 dataset_name: 'DB_CE_TEMP'
 bq_table: 'EMPLOYEE_1'
 cloudsql_database: 'postgres'
 cloudsql_table: 'EMPLOYEE_1' 
 cloudsql_staging_table: 'STAGING_EMPLOYEE_1'
 type_load: 'HIST'     # Type of load must be defined : HIST/INCR
 
 
EMPLOYEE_2 : #table 2
 project_name : 'dmgcp-del-ce'
 dataset_name: 'DB_CE_TEMP'
 bq_table: 'EMPLOYEE_2'
 cloudsql_database: 'postgres'
 cloudsql_table: 'EMPLOYEE_2' 
 cloudsql_staging_table: 'STAGING_EMPLOYEE_2'
 type_load: 'HIST'     # Type of load must be defined : HIST/INCR
 
 
 
 
